name: "dashy"
services:
  dashy:
    image: lissy93/dashy
    hostname: dashy
    container_name: Dashy
    volumes:
      - dashy_data:/app/user-data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
          cloudflared-network: null
networks:
  cloudflared-network:
    name: cloudflared-network
    external: true
volumes:
 dashy_data: